### ISSUE TITLE
PagePark plug-ins documentation incorrect

### ISSUE THREAD

**Issue by andrewshell** [scripting/pagePark#16]
I took a look at the documentation here:
http://pagepark.io/docs/plugins.md

This does not appear to work anymore with the current version of pagePark.

Based on reading through the code the contents of filter.js are pulled into a wrapper:

```js
module.exports = function (options, localStorage, system) {
    // filter.js contents
    }
```

and options is an object with two keys, httpRequest and serveLocalFile.

`serveLocalFile` only takes a filename.  It does not appear that the callback with code, type and val is available anymore.

**Comment by scripting** [comment]
Andrew, thanks for this report. :smile:

I just spent about ten minutes looking into this, and it appears that I did change the way plugins work without changing the docs. Not sure why, or when this happened, but I do have notes that will probably explain, and I will look into it, and at some point fix the docs.

Before continuing -- I wanted to know -- is your report basically "Hey Dave, the docs don't match the functionality!" or is there more to it? It looks like the current way is simpler, and we know it works, because a plugin is doing the work for my.this.how.

**Comment by scripting** [comment]
Update: This change is explained in this update note, as is the fact that the docs are out of sync now. 

https://github.com/scripting/pagePark#v0810-51020-by-dw

I learned about something really important -- [requireFromString](https://www.npmjs.com/package/require-from-string). It de-klooged this stuff. Made it really work. 

I probably have some more notes on this. 

This is kind of on-topic for what we were talking about. I have a pretty good note-taking system these days. 

And I'm going to keep saying this -- I'm _really_ glad you're reviewing this stuff Andrew. You can see how hard it is working on this stuff with no one on the other side of the APIs. Lots of mistakes get made that would otherwise be caught.
